# Use the official Node.js 16 as a parent image
FROM node:16


# Set the working directory inside the container to /app
WORKDIR /app

# Install the Vue CLI globally using npm
RUN npm install -g @vue/cli

# Command to run your app using CMD which defines your runtime
CMD ["bash"]
